name: base
channels:
  - conda-forge
dependencies:
  # People still wanna pull stuff, even if into RStudio
  - nbgitpuller==1.2.*
  # Based on request
  # https://2i2c.freshdesk.com/a/tickets/5448
  - otter-grader==6.1.*
  - pip
  - pip:
      # For pulling from private repositories
      - git-credential-helpers==0.2
